// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_hard_core = "CgkI5fXjpJcUEAIQAg"; // <GPGSID>
        public const string achievement_game_begins = "CgkI5fXjpJcUEAIQAA"; // <GPGSID>
        public const string achievement_250k_run = "CgkI5fXjpJcUEAIQBA"; // <GPGSID>
        public const string achievement_game_addict = "CgkI5fXjpJcUEAIQBg"; // <GPGSID>
        public const string achievement_crash_master = "CgkI5fXjpJcUEAIQBw"; // <GPGSID>
        public const string achievement_shame_less = "CgkI5fXjpJcUEAIQAQ"; // <GPGSID>
        public const string achievement_350k_run = "CgkI5fXjpJcUEAIQBQ"; // <GPGSID>
        public const string leaderboard_all_time_best = "CgkI5fXjpJcUEAIQCQ"; // <GPGSID>
        public const string achievement_150k_run = "CgkI5fXjpJcUEAIQAw"; // <GPGSID>

}

